[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://biosticker-backend-9178b2fa5a35.herokuapp.com/api"

[context.deploy-preview.environment]
  VITE_API_URL = "https://biosticker-backend-9178b2fa5a35.herokuapp.com/api" 